### ISSUE TITLE
Lacks Documentation

### ISSUE THREAD

**Issue by postmodern** [AE9RB/ruby-redis#3]
One of my major problems with [redis-rb](https://github.com/ezmobius/redis-rb) was it's total lack of documentation, which made it difficult to determine what Object types would be returned/yielded from various methods. It would be totally rad if ruby-redis had full [YARD](http://yardoc.org/) documentation with @param, @yield, @return and @raise tags.

**Comment by AE9RB** [comment]
You should write and submit docs to redis-rb after you figure things out so that others don't hit the same bumps.

Ruby-redis is not a clone of redis-rb (a client).  It is a clone of Redis (the server) which is already documented.  If you have specific ideas for ruby-redis documentation, please submit a patch.

**Comment by AE9RB** [comment]
Here's a conversion that should be accurate for any of the client libraries, including the one I just added to ruby-redis.  You might find it helpful when working with redis-rb or any other Ruby library.
String === Status reply
RuntimeError === Error reply
String === Bulk reply
Integer === Integer reply
Array === Multi-bulk reply
NilClass === Nil element or nil multi-bulk

**Comment by postmodern** [comment]
@dturnbull Thank you. Although, there are some methods in redis-rb which accept arbitrary number of arguments, such as `brpop`. When I have some extra time, I'll try contributing some documentation to redis-rb.
